services:
  - type: web
    name: ADC-web-dev
    env: docker
    plan: free
    branch: main
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://adc-web-dev.onrender.com
